---
name: 🍎 Check (MacOS)

on:
  push:
    branches: [main]
    paths:
      - "lib/sh/**"
  pull_request:
    branches: [main]
    paths:
      - "lib/sh/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: ☑️ ShellCheck
        uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca
        with:
          scandir: "./lib/sh"

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [shellcheck]
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: ⚙️  Prepare dependencies
        run: |
          brew install zsh
      - name: "⚙️  Check: install.sh -- -i skip"
        run: sh -x ./lib/sh/install.sh -- -i skip; command rm -rf ~/.zi
      - name: "⚙️  Check: install.sh -- -i annex"
        run: sh -x ./lib/sh/install.sh -- -a annex; command rm -rf ~/.zi
      - name: "⚙️  Check: install.sh -- -i loader"
        run: sh -x ./lib/sh/install.sh -- -a loader; command rm -rf ~/.zi
      - name: "⚙️  Check: install.sh -- -i zunit"
        run: sh -x ./lib/sh/install.sh -- -a zunit; command rm -rf ~/.zi
      - name: "⚙️ Check: install_zpmod.sh"
        run: sh -x ./lib/sh/install_zpmod.sh
      - name: ⚙️ Load zpmod module
        run: |
          module_path+=( "$HOME/.zi/zmodules/zpmod/Src" )
          zmodload zi/zpmod
          zpmod source-study -l
        shell: zsh {0}
