---
name: "♻️ Sync Labels"
on:
  schedule:
    - cron: "22 2 * * 2"
  workflow_dispatch:
jobs:
  labels:
    name: "♻️ Sync labels"
    uses: z-shell/.github/.github/workflows/sync-labels.yml@91068ee88e8788deff439d6ee36b77329edeb98a # v1.0.8
