---
name: "⭕ Trunk"
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: "0 07 * * 5"
    - cron: "0 01 * * 1"
  workflow_dispatch: {}

jobs:
  check:
    if: github.event.schedule != '0 07 * * 5'
    name: "⚡ Check"
    uses: z-shell/.github/.github/workflows/trunk.yml@91068ee88e8788deff439d6ee36b77329edeb98a # v1.0.8
  upload:
    if: github.event.schedule == '0 07 * * 5'
    name: "🆙 Upload"
    uses: z-shell/.github/.github/workflows/trunk.yml@91068ee88e8788deff439d6ee36b77329edeb98a # v1.0.8
    secrets:
      trunk-token: ${{ secrets.TRUNK_TOKEN }}
  upgrade:
    if: github.event.schedule == '0 01 * * 1'
    name: "✨ Upgrade"
    uses: z-shell/.github/.github/workflows/trunk.yml@main
    with:
      action: upgrade
