---
name: "⭕ Trunk"
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: "0 07 * * 5"
  workflow_dispatch: {}

jobs:
  check:
    if: github.event.schedule != '0 07 * * 5'
    name: "⚡"
    uses: z-shell/.github/.github/workflows/trunk.yml@v1.0.6
  upload:
    if: github.event.schedule == '0 07 * * 5'
    name: "🆙"
    uses: z-shell/.github/.github/workflows/trunk.yml@v1.0.6
    secrets:
      trunk-token: ${{ secrets.TRUNK_TOKEN }}
